close all
clear

t = [0.0 1.0 2.0 3.0 4.0 5.0];
y = [1.0 2.7 5.8 6.6 7.5 9.9];
yp = [1.0 2.7 5.8 6.7 7.5 9.9];
xx = linspace(0,5,101);
%figure
%hold on;
% p1 = plot(t,y,'r*');

fprintf('a)\n\tWith Original y''s derivatives at different t''s:\n');

for n = 0:1:5
    f = polyfit(t,y,n);
    fd = polyder(f);
    fdval = polyval(fd,t);
    fprintf('\t\tdegree=%.0f  %.3f %.3f %.3f %.3f %.3f %.3f\n', n, fdval(1), fdval(2), fdval(3), fdval(4), fdval(5), fdval(6));
    yy = polyval(f,xx);
    %h(n+1) = plot(xx,yy);
end

%xlabel('X Axis');ylabel('Y Axis');title('Polynomial Interpollation');
%legend([h,p1],'degree 0','degree 1','degree 2','degree 3','degree 4','degree 5','Known points','location','northwest');
% hold off;
%%
%f1 = figure();

fprintf('\n\tWith perturbated y''s(y(4) = 6.7) derivatives at different t''s:\n');
for n = 0:1:5
    f = polyfit(t,yp,n);
    fd = polyder(f);
    fdval = polyval(fd,t);
    fprintf('\t\tdegree=%.0f  %.3f %.3f %.3f %.3f %.3f %.3f\n', n, fdval(1), fdval(2), fdval(3), fdval(4), fdval(5), fdval(6));
end

pp = spline(t,y);
fprintf('b)\n\tWith Original y''s derivatives at different t''s:\n');
fprintf('\t\t%.3f %.3f %.3f %.3f %.3f %.3f\n',...
    polyval(polyder(pp.coefs(1,:)), t(1)),...
    polyval(polyder(pp.coefs(2,:)), t(2)),...
    polyval(polyder(pp.coefs(3,:)), t(3)),...
    polyval(polyder(pp.coefs(4,:)), t(4)),...
    polyval(polyder(pp.coefs(5,:)), t(5)),...
    polyval(polyder(pp.coefs(5,:)), t(6)));

% p2 = plot(t,y,'*',xx,ppval(pp,xx)); hold on;

pp = spline(t,yp);
fprintf('\n\tWith Perturbated y''s derivatives at different t''s:\n');
fprintf('\t\t%.3f %.3f %.3f %.3f %.3f %.3f\n',...
    polyval(polyder(pp.coefs(1,:)), t(1)),...
    polyval(polyder(pp.coefs(2,:)), t(2)),...
    polyval(polyder(pp.coefs(3,:)), t(3)),...
    polyval(polyder(pp.coefs(4,:)), t(4)),...
    polyval(polyder(pp.coefs(5,:)), t(5)),...
    polyval(polyder(pp.coefs(5,:)), t(6)));

pp = csaps(t,y,0.8);
fprintf('c)\n\tWith Original y''s derivatives at different t''s:\n');
fprintf('\t\t%.3f %.3f %.3f %.3f %.3f %.3f\n',...
    polyval(polyder(pp.coefs(1,:)), t(1)),...
    polyval(polyder(pp.coefs(2,:)), t(2)),...
    polyval(polyder(pp.coefs(3,:)), t(3)),...
    polyval(polyder(pp.coefs(4,:)), t(4)),...
    polyval(polyder(pp.coefs(5,:)), t(5)),...
    polyval(polyder(pp.coefs(5,:)), t(6)));

% p3 = plot(t,y,'*',xx,ppval(pp,xx)); 

pp = csaps(t,yp,0.8);
fprintf('\n\tWith Perturbated y''s derivatives at different t''s:\n');
fprintf('\t\t%.3f %.3f %.3f %.3f %.3f %.3f\n',...
    polyval(polyder(pp.coefs(1,:)), t(1)),...
    polyval(polyder(pp.coefs(2,:)), t(2)),...
    polyval(polyder(pp.coefs(3,:)), t(3)),...
    polyval(polyder(pp.coefs(4,:)), t(4)),...
    polyval(polyder(pp.coefs(5,:)), t(5)),...
    polyval(polyder(pp.coefs(5,:)), t(6)));

pp = pchip(t,y);
fprintf('d)\n\tWith Original y''s derivatives at different t''s:\n');
fprintf('\t\t%.3f %.3f %.3f %.3f %.3f %.3f\n',...
    polyval(polyder(pp.coefs(1,:)), t(1)),...
    polyval(polyder(pp.coefs(2,:)), t(2)),...
    polyval(polyder(pp.coefs(3,:)), t(3)),...
    polyval(polyder(pp.coefs(4,:)), t(4)),...
    polyval(polyder(pp.coefs(5,:)), t(5)),...
    polyval(polyder(pp.coefs(5,:)), t(6)));

% p4 = plot(t,y,'*',xx,ppval(pp,xx)); 

pp = pchip(t,yp);
fprintf('\n\tWith Perturbated y''s derivatives at different t''s:\n');
fprintf('\t\t%.3f %.3f %.3f %.3f %.3f %.3f\n',...
    polyval(polyder(pp.coefs(1,:)), t(1)),...
    polyval(polyder(pp.coefs(2,:)), t(2)),...
    polyval(polyder(pp.coefs(3,:)), t(3)),...
    polyval(polyder(pp.coefs(4,:)), t(4)),...
    polyval(polyder(pp.coefs(5,:)), t(5)),...
    polyval(polyder(pp.coefs(5,:)), t(6)));

% p5 = plot(t,y,'r*');
% xlabel('X Axis');ylabel('Y Axis');title('Interpollation');
% legend([p2(2),p3(2),p4(2),p5],...
%     'Cubic Spline InterPollation',...
%     'Smooth Spline Interpollation',...
%     'HermiteCubic Interpollation',...
%     'Known Points',...
%     'Location','northwest');