all: noPivot partial complete

noPivot: 2_11.c
	gcc 2_11.c -o noPivot

partial: 2_11_partialPivot.c 
	gcc 2_11_partialPivot.c -o partial

complete: 2_11_completePivot.c
	gcc 2_11_completePivot.c -o complete
	
clean:
	rm noPivot partial complete

